#!/bin/bash

if which ksshaskpass &> /dev/null ; then
    #SSH_ASKPASS=$(which ksshaskpass)

    # when some identities are already loaded, the exit code is 0
    # when no identity is loaded, the exit code of is '1'
    if ssh-add -l &> /dev/null ; then
        # if already loaede, do not bother anymore
        true
    else
        ssh-add < /dev/null
    fi

fi

