# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.places.importBookmarksHTML", true);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.smartBookmarksVersion", 0);
user_pref("font.default.x-western", "DejaVu Sans YuanTi");
user_pref("font.default.zh-CN", "DejaVu Sans YuanTi");
user_pref("font.minimum-size.zh-CN", 13);
user_pref("font.name.fixed.x-western", "Monospace");
user_pref("font.name.monospace.zh-CN", "DejaVu Sans YuanTi Mono");
user_pref("font.name.sans-serif.zh-CN", "DejaVu Sans YuanTi");
user_pref("font.name.serif.zh-CN", "DejaVu Sans YuanTi");
user_pref("font.name.variable.x-western", "Sans");
//user_pref("intl.charset.detector", "universal_charset_detector");
user_pref("intl.charset.detector", "zhcn_parallel_state_machine");
