" detect filetype baseupon filename

augroup filetypedetect

    " Recognize standard C++ headers
    autocmd BufRead /usr/include/c++/*  setfiletype cpp

    " recognize log file generated by syslog
    autocmd BufRead /var/log/*log*      setfiletype messages

augroup end
